feature: dev 186 - visualizar practicas vencidas
Equipo102ProyectoUNLaM/trida pull request #104
Opened 2020-09-24 03:43 UTC by LautaroPerez

En este *PR* se agrega la funcionalidad de ver las prácticas vencidas y actuales por separado.

__Para probar:__
* Ingresar a la sección de prácticas
* Ver que el titulo y los nombres de los botones están bien.
* Ver que las prácticas listadas no estén vencidas.
* Presionar en "ver prácticas vencidas" y verificar el titulo, botones y prácticas listadas.
* Verificar que las prácticas vencidas no se pueden editar, borrar o cambiar fechas.

**Reviewer puede mergear**

2020-09-24 14:59 UTC, julieta-foglia requested changes
-Como alumno también volaría las acciones de practicas vencidas (actualmente se ven botones de subir práctica y descargar práctica).
-Agregaría un margin entre el botón de agregar práctica y ver practicas vencidas
<img width="438" alt="Screen Shot 2020-09-24 at 11 54 46" src="https://user-images.githubusercontent.com/31071987/94162658-52a24000-fe5d-11ea-867d-43e02e0dd194.png">

2020-09-24 14:59 UTC, julieta-foglia commented on front/src/lang/locales/es_ES.js
> +  'menu.my-activities': 'Mis Prácticas actuales',
pondría 'Mis Prácticas Actuales' y 'Mis Prácticas Vencidas' (actuales y vencidas en mayuscula)

2020-09-24 16:20 UTC, LautaroPerez commented on front/src/lang/locales/es_ES.js
> +  'menu.my-activities': 'Mis Prácticas actuales',
Excelente!

2020-09-24 16:20 UTC, LautaroPerez commented
@julieta-foglia Arregladito!

2020-09-24 22:17 UTC, micaderito reviewed
Exxxxplendido, solo dos cosas:
- No le pondría "vencidas", ya que incluye las que finalizaron y entregó. Les pondría "Finalizadas"
- Dentro de las finalizadas, agregaría un badge que diga "entregada" en azul, o "sin entregar" en rojo. Del estilo como hice en la PR que mandé de características. Podés ver en evaluaciones como lo hago, busco en correcciones si hay alguna de ese usuario para esa evaluación.
![image](https://user-images.githubusercontent.com/26844750/94205717-3f619580-fe9a-11ea-8fa0-479f5a12179f.png)

2020-09-25 20:55 UTC, julieta-foglia approved these changes

2020-09-26 00:56 UTC, micaderito approved these changes
harrrrrrrrmasa

2020-09-26 01:56 UTC, merged