se desarrolla importar evaluacion
Equipo102ProyectoUNLaM/trida pull request #107
Opened 2020-09-26 17:04 UTC by maticairo

2020-09-30 22:57 UTC, LautaroPerez approved these changes
Fabulosooo

2020-09-30 22:57 UTC, LautaroPerez commented on front/src/pages/app/evaluaciones/detalle-evaluacion/agregar-evaluacion.js
> +      console.log('evaluacion.id', evaluacionesDesencriptadas[0].id);
```suggestion
```

2020-09-30 23:26 UTC, micaderito requested changes
Agregaría una validación para verificar la extensión del archivo que sube. Porque subi un pdf y se rompió. Supongo que para hacer esto hay que cambiar el componente con el que se suben las cosas, asique usaría el que se usa en evaluaciones asi queda todo con el mismo estilo

2020-10-06 00:52 UTC, LautaroPerez approved these changes

2020-10-07 19:29 UTC, julieta-foglia approved these changes

2020-10-07 23:14 UTC, micaderito approved these changes
Perfectooo

2020-10-07 23:20 UTC, merged