feature:dev 244 - Tab de Respuestas de alumnos a preguntas lanzadas
Equipo102ProyectoUNLaM/trida pull request #121
Opened 2020-10-11 20:37 UTC by ThomiReynoso

En este PR se agrega la funcionalidad de calcular y mostrar en un gráfico las respuestas de los alumnos a las preguntas lanzadas.

**Test Plan**

- Como docente, lanzar preguntas. Como alumno, responderlas. 
- Luego, ir a la tab de _Respuestas_ y visualizar los gráficos armados para cada pregunta. _No está hecho en tiempo real, por lo que quizás haya que darle f5 o salir y volver a entrar a la clase para que actualice los datos_

![image](https://user-images.githubusercontent.com/26986556/95689605-50bfd700-0be8-11eb-8a39-d90d45a92078.png)

_NOTA: Hay una pequeña mejora de código. Estoy usando_  `var preguntasConRespuestasDeAlumnosGlobal = [];` , _ya que por algún motivo, no se setea correctamente el hook_ `preguntasConRespuestasDeAlumnos` _en la linea **35** (creo que es un tema de sincronismo, pero no pude resolverlo. Algo similar me pasó en el PR de Responder Preguntas (#119 ) )._

2020-10-11 22:57 UTC, micaderito approved these changes

2020-10-12 21:48 UTC, julieta-foglia requested changes
1. El setPreguntasConRespuestasDeAlumnos no se está haciendo porque el array de objetos que está tratando de setear contiene cosas que no se pueden setear, ejemplo los objetos __proto__. Hay que guardar solo lo que se necesita realmente.
<img width="514" alt="Screen Shot 2020-10-12 at 18 46 12" src="https://user-images.githubusercontent.com/31071987/95793110-41f62480-0cbb-11eb-8128-9f6dbab87dc9.png">

2. Se puede usar una clase en lugar de un componente funcional acá 🤔

2020-10-15 01:58 UTC, julieta-foglia commented
@ThomiReynoso  Thomi, dos cosas, lo último:
En el `if (preguntasEncriptadasConRespuestas.length > 0)` por el else tiene que setear el loading en false, si no hay preguntas queda cargando infinitamente.

Por otro lado, en el render, si respuestas por pregunta está vacío tiene que mostrar un mensaje:
```
{isEmpty(respuestasPorPregunta) && (
        <span>No hay respuestas cargadas</span>
)}
```

2020-10-16 00:02 UTC, julieta-foglia approved these changes

2020-10-16 23:47 UTC, merged