feature/DEV-310: se deshabilita seleccion de fechas anteriores en form clase
Equipo102ProyectoUNLaM/trida pull request #135
Opened 2020-10-18 13:48 UTC by julieta-foglia

Probar que en form clase no se puedan seleccionar fechas previas a la de hoy.

**MERGEAR DESPUES DEL 301!!!**

2020-10-19 00:04 UTC, LautaroPerez reviewed
Excelente! Podriamos agregarlo en evaluaciones escritas y orales? Y otro detalle que nose si se podrá, con las horas se puede validar lo mismo?

2020-10-19 01:10 UTC, julieta-foglia commented
Listo @LautaroPerez !

2020-10-19 14:59 UTC, LautaroPerez approved these changes
Excelenchi, lo unico que agregaría es si se pueden ver los dias del calendar en gris como se ve las horas que no se pueden seleccionar (thomi diria es un nice to have)

2020-10-20 01:17 UTC, micaderito requested changes
Joya juli, solo unas cosas:

- Haciendo foco y saliendo del campo me muestra el tooltip del error, eso ta ok, pero dsp borro a mano la fecha y tira este tooltip
![image](https://user-images.githubusercontent.com/26844750/96528299-b3544b00-1258-11eb-9371-4da21239ba76.png)

- Le pondría el autocomplete = OFF a la fecha

- Quise crear una clase hoy a las 23, (siendo las 22) y no me deja
![image](https://user-images.githubusercontent.com/26844750/96528335-d3840a00-1258-11eb-97f5-8bf0e5bce4a0.png)

2020-10-22 00:43 UTC, maticairo approved these changes

2020-10-22 01:14 UTC, micaderito approved these changes

2020-10-22 01:19 UTC, merged