<NO MERGE - WIP> Feature/dev 184 - Corregir evaluacion
Equipo102ProyectoUNLaM/trida pull request #146
Opened 2020-10-22 00:43 UTC by maticairo

2020-10-23 21:43 UTC, micaderito requested changes
Agregué un cambio en la redirección al editar una evaluación, había quedado sin el /escritas y la correccion de preguntas aleatorias. 
Solo cosillas:

- Entregué una evaluación y como alumno  y docente en correcciones me aparece "Descargar práctica" , debería decir descargar evaluacion
![image](https://user-images.githubusercontent.com/26844750/97056357-2ca4b400-155f-11eb-8d0e-4ea409fd46e7.png)
- En el tipo de ejercicio choice con imágenes no me cargó las fotitos 
![image](https://user-images.githubusercontent.com/26844750/97056522-92913b80-155f-11eb-952f-67c589e5ac08.png)
- Hay comentarios en la consola, los volaría

Después terrible todo Mati, me encanta!

2020-10-24 15:03 UTC, julieta-foglia commented
Matii, hay que agregar que cuando se genera la corrección en la DB (antes de que se corrija) se le agreguen los campos: 
`comentarioCorreccion`,
`estadoCorreccion` (para el aprobado, desaprobado o reentrega)
`notaCorreccion`

Así como está en las correcciones de las prácticas. El docente cuando pone 'Enviar Correccion' completa estos campos.

2020-10-24 15:09 UTC, julieta-foglia approved these changes

2020-10-26 20:32 UTC, micaderito approved these changes

2020-10-26 20:33 UTC, merged