feature:dev 324 - reporte de asistencias y preguntas anonimas en clases
Equipo102ProyectoUNLaM/trida pull request #162
Opened 2020-10-29 03:21 UTC by LautaroPerez

En este **PR** se agrega el reporte de asistencia y preguntas anonimas realizadas por cada alumno en las clases.

__Para probar:__
* Ingresar a los reportes por clase (como docente y directivo)
* Ver que los reportes coinciden con lo existente en la base de datos.

2020-10-29 20:06 UTC, julietafoglia approved these changes

2020-10-30 11:26 UTC, ThomiReynoso commented on front/src/pages/app/reportes/reportes-clases.js
> +    let clases = await Promise.all(clasesPromise);
Para que sirve el `Promise.all`?

2020-10-30 11:45 UTC, ThomiReynoso requested changes
Si clickeo en la opcion "Reportes" del breadcrumb, me lleva a la pagina de error. Supongo que porque no existe `http://localhost:3000/app/reportes` todavia

2020-10-30 18:52 UTC, julieta-foglia commented
> Si clickeo en la opcion "Reportes" del breadcrumb, me lleva a la pagina de error. Supongo que porque no existe `http://localhost:3000/app/reportes` todavia

@LautaroPerez @ThomiReynoso  Yo lo arreglé en la PR del 322

2020-10-30 23:33 UTC, micaderito reviewed
Joya lauti! Solo dos cosas:

- Me genera un toc que se alineen diferente las columnas, se puede fijar? 
![image](https://user-images.githubusercontent.com/26844750/97764930-0054de80-1aef-11eb-9f30-4ae470a91477.png)

- Ordenaría lo que se muestra al revés, es decir, que se muestre la fecha más reciente primero, para no tener que ir abajo de todo para ver lo último

2020-10-31 02:22 UTC, ThomiReynoso approved these changes
Fabulosito

2020-10-31 02:25 UTC, merged