feature/DEV-322: se agrega reporte editable
Equipo102ProyectoUNLaM/trida pull request #165
Opened 2020-10-30 18:49 UTC by julieta-foglia

Para probar, navegar a Reportes > Mi Reporte y generar un reporte.
Este ticket no contempla el guardado en la DB, solo la generación del PDF.

2020-10-30 23:56 UTC, micaderito requested changes
JULI ME ENCANTA! Te zarpaste

Unas cosillas: 

- Puse una columna más del límite y se fue para abajo. Quizás se puede achicar las demas cards hasta un cierto punto y dsp que no se agreguen mas columnas, para que no rompa nada, o meter un scroll horizontal (nose que tan complicado será, pero estaría copado porque no lo limitas)
![image](https://user-images.githubusercontent.com/26844750/97765547-4f9c0e80-1af1-11eb-9f91-c81c56aa5110.png)

- Le pondría en vez de "Mis reportes" "Planilla" o "Mi planilla" que es como la llaman normalmente los docentes, y para que también entienda que la va a poder editar

- Una boludez pero, se puede hacer que al presionar enter en el campo donde ingresas el nombre ya cree la columna?

- Centraría en su fila al nombre del alumno y quizás metería una linea divisoria entre cada fila 
![image](https://user-images.githubusercontent.com/26844750/97765677-c9cc9300-1af1-11eb-812e-8e8703b8c01c.png)

- Al exportar pdf lo mismo, le pondría de nombre "planilla" y la fecha quizás. Nose que tan complicado es agregarle cosas al pdf, pero por ahí se podrían cargar más datos como la materia, el curso, la fecha

- Cuando no cargas nada en el campo, aparece en el pdf el placeholder 
![image](https://user-images.githubusercontent.com/26844750/97765755-17490000-1af2-11eb-8005-f4a5f93e96a0.png)

2020-10-31 16:29 UTC, julieta-foglia commented
@micaderito Mica creo que hice todo menos lo del placeholder, no me parece mal que se muestre si no ingresó y es un quilombo de sacar en el pdf. Lo que puedo hacer es sacar el placeholder del input y listo

2020-10-31 17:02 UTC, micaderito approved these changes
Exxxxxxxxxxxxcelente

2020-10-31 17:10 UTC, maticairo approved these changes

2020-10-31 17:15 UTC, merged