feature/DEV-335 - Validacion de extensiones en subir practicas
Equipo102ProyectoUNLaM/trida pull request #166
Opened 2020-10-31 13:50 UTC by maticairo

Probar que para subir una práctica solo se pueda con imagenes jpg, jpeg o png, o archivos pdf.

2020-10-31 15:26 UTC, micaderito requested changes
Desde windows puedo cambiar abajo para elegir otro archivom habría que cambiar el componente como dijo Juli.
Otra cosa que no es de esta PR pero una vez que subis una practica no se refresca la lista con el cartel entregada. Si refresco aparece pero me sigue dejando subir una práctica, esta bien ?

2020-11-07 14:22 UTC, julieta-foglia requested changes
Solo el comentario, el resto todo piola

2020-11-07 14:22 UTC, julieta-foglia commented on front/src/pages/app/practicas/form-subir-practica.js
> +      const fileExtension = file.name.split('.')[1];
Mati, acá habría que validar que tome el último 'split' porque me paso que subi un archivo que tenía puntos en el medio y agarró cualquier cosa de extensión.

2020-11-07 16:19 UTC, julieta-foglia approved these changes

2020-11-07 18:34 UTC, micaderito approved these changes
Excelente mati

2020-11-07 18:34 UTC, merged