feature: DEV-341 - agregar foto a clase y foro
Equipo102ProyectoUNLaM/trida pull request #169
Opened 2020-11-04 03:55 UTC by LautaroPerez

En este **PR** se agrega la posibilidad de agregar fotos a las clases y foros.

__Para probar:__
* Agregar una nueva clase cargandole una foto. (Ver que se carga correctamente en el storage)
* Editar una clase existente agregandole una foto.
* Hacer lo mismo con los foros

**Reviewer puede mergear**

2020-11-04 16:33 UTC, micaderito requested changes
Geniallllllllllllllll

Cosillas: 
- Se puede hacer que cuando cargo la foto se previsualice y cambie la que aparece por defecto? Podes fijarte como lo hice en adjuntar desarrollo en evaluaciones 
![image](https://user-images.githubusercontent.com/26844750/98138389-cf372e00-1ea1-11eb-93ad-94e7b650dbdf.png)
- Se puede agregar una X para eliminar la foto existente y que vuelva a aparecer la que viene por defecto? Es de hincha bolas, si es mucho bardo ya fue
- Agregué como foto un excel y rompí todo je. Validaría que solo se puedan cargar imágenes. En el mismo archivo de adjuntar desarrollo en evaluaciones se hace

2020-11-04 18:15 UTC, julieta-foglia commented
Me en can tó

2020-11-04 18:15 UTC, julieta-foglia approved these changes

2020-11-05 02:20 UTC, LautaroPerez commented
@micaderito LOS CAMBIOS HAN SIDO REALIZADOS :artificial_satellite:

2020-11-05 13:59 UTC, maticairo approved these changes

2020-11-05 19:48 UTC, micaderito approved these changes
exxxxxxxxxxxxxxxxxxxxcelent

2020-11-05 19:48 UTC, merged