Feature/dev 345 - Correcciones responsive
Equipo102ProyectoUNLaM/trida pull request #176
Opened 2020-11-07 00:30 UTC by micaderito

En esta PR se corrigen cosas en mobile y web.
Probar: 

- No mostrar grilla editable en mobile
- Sacar boton pizarron en mobile
- Boton volver de foro en web que se vea a la derecha. (y que se vea bien en mobile)
- Calendario en web como estaba antes (dos columnas)
- Boton de selección de curso más grande (web y mobile)
- Se corrige margen en Calendario para editar fechas de evaluacion desde el listado
- Se acomoda tachito de eliminar mensaje en foro en mobile
- Corrección en modal de editar preguntas mobile (Celu thomi)

2020-11-07 01:53 UTC, ThomiReynoso requested changes
Algunas cositas que encontré:
- Ni bien mando un msj, y estoy en la tab de enviados, al terminar de mandar, muestra el ID (si cambiás de tab y volves, ya se muestra bien el nombre )
- En reenviar un mensaje, también pasa lo mismo
![image](https://user-images.githubusercontent.com/26986556/98428918-7c689c80-2082-11eb-882b-1e4c04448deb.png)

- Nombres largos se ven medio chingados
![image](https://user-images.githubusercontent.com/26986556/98428984-d23d4480-2082-11eb-9a91-eef0df109546.png)

2020-11-07 16:31 UTC, julieta-foglia commented
Mica, lo unico que vi fue el boton de volver del foro que quedó medio raro
![WhatsApp Image 2020-11-07 at 13 31 01](https://user-images.githubusercontent.com/31071987/98446630-8aa7ce80-20fd-11eb-8232-01e1983b2e96.jpeg)

2020-11-07 16:35 UTC, julieta-foglia requested changes
Solo el comentario, el resto genial

2020-11-07 18:51 UTC, LautaroPerez approved these changes

2020-11-07 22:21 UTC, julieta-foglia approved these changes

2020-11-09 21:54 UTC, ThomiReynoso approved these changes
Fabulosito

2020-11-09 22:17 UTC, merged