Feature/DEV-195 - Subir archivos en practica por el docente
Equipo102ProyectoUNLaM/trida pull request #73
Opened 2020-09-01 22:56 UTC by maticairo

Para probar:
 - Ingresar como docente y crear una nueva práctica adjuntando un archivo.

Verificar que:
 - Se cree en el storage un nuevo input bajo la ruta idMateria/practicas/id
 - En el documento de la practica tenga la propiedad idArchivo con el id correspondiente
 - En el front se pueda descargar el archivo

2020-09-03 21:47 UTC, julieta-foglia approved these changes

2020-09-03 21:53 UTC, julieta-foglia commented on front/src/pages/app/practicas/form-practica.js
> +                style={{
Mover este estilo al archivo de estilos _trida.style.scss y referenciarlo desde la label como className="[estilo]"

2020-09-03 21:54 UTC, julieta-foglia commented on front/src/pages/app/practicas/form-practica.js
> +                style={{
Ponerle de background color el $theme-color-1

2020-09-03 21:54 UTC, julieta-foglia requested changes
Solo por el cambio chiquito del estilo

2020-09-04 14:34 UTC, julieta-foglia approved these changes

2020-09-04 20:25 UTC, LautaroPerez approved these changes
Funciona fabuloso. Dejo algunos detalles para ver cuando se pueda:
- Agregar un loading mientas carga el documento.
- Cuando descargamos un archivo (un word por ejemplo), se descarga con un el id que se guarda en el storage. Podriamos ponerle el nombre de la practica.
- Ingresando como alumno, se ve el icono de descargar a la izquierda, podriamos ponerlo al final de la fila. (Se puede ver cuando se haga el entregar practica)

2020-09-04 20:26 UTC, merged