feature/dev 250: validación y encriptación de los mensajes
Equipo102ProyectoUNLaM/trida pull request #85
Opened 2020-09-07 20:59 UTC by ThomiReynoso

En este PR  se agrega:

- Validación por el campo "mensaje" (el texto o contenido del mismo) al enviar/responder un mensaje.
- Validación de que si no selecciona ningún recepetor, no habilita el botón _enviar_. 
- Se encripta el contenido del mensaje en la DB.

Para probar: 
-  Enviar, responder, reenviar mensajes. 
-  Verificar que todos los mensajes tienen su "contenido" encriptado en la DB, pero que se visualiza ok en Trida.
-  Verificar las validaciones mencionadas al principio.

2020-09-07 23:20 UTC, micaderito reviewed
- Al reenviar un mensaje enviado, no me deja editar el texto que está en el textarea
- Los mensajes pueden enviarse sin Asunto

2020-09-07 23:43 UTC, ThomiReynoso commented
> * Al reenviar un mensaje enviado, no me deja editar el texto que está en el textarea
> * Los mensajes pueden enviarse sin Asunto

- Inicialmente lo hice así porque lo habiamos charlado en una meeting, pero ahi pushié para que el **asunto** sea requerido tambien
- Con respecto a no editar el mensaje a reenviar, es algo que ya estaba hecho desde antes

2020-09-08 01:42 UTC, micaderito approved these changes

2020-09-08 02:57 UTC, LautaroPerez requested changes
![image](https://user-images.githubusercontent.com/31162985/92428546-c8bc5c80-f165-11ea-98ef-303c77b3d049.png)

El mensaje a responder no se ve todo :( Y otro detalle, el margen de los campos deshabilitados no es el mismo que los otros

2020-09-08 18:34 UTC, ThomiReynoso commented
@LautaroPerez fixeadito ambas cosas

2020-09-08 18:42 UTC, LautaroPerez approved these changes
Genial

2020-09-08 23:12 UTC, merged