feature/DEV-275: se agrega posibilidad de agregar links a clase
Equipo102ProyectoUNLaM/trida pull request #86
Opened 2020-09-07 21:19 UTC by julieta-foglia

Esta PR agrega la incorporación de links a contenidos de clase.
Para probar:
1- Navegar a una clase, pestaña contenidos
2- Aparece nueva sección 'Links asociados'
3- Probar de agregar y remover links desde la modal de Asociar Links
4- Probar que se pueda navegar a los links agregados

2020-09-08 01:54 UTC, micaderito reviewed
Quedó re bien juuu, solo estas cosas: 
- Cuando tengo un solo link y quiero eliminarlo, no puedo porque desaparece el botón
- Le agregaría a los links algún título o descripción, para que sepan de que se trata cuando lo vean

2020-09-08 03:04 UTC, LautaroPerez requested changes
Se podría agregar alguna validación para saber que son de tipo url?

2020-09-08 16:27 UTC, julieta-foglia commented
@LautaroPerez @micaderito todo arreglado

2020-09-08 17:13 UTC, LautaroPerez approved these changes
EXCELLENTE

2020-09-08 23:21 UTC, ThomiReynoso requested changes
- Podemos poner el `autocomplete=off` en ambos campos? Para que no aparezcan sugerencias de cosas que pusimos previamente
![image](https://user-images.githubusercontent.com/26986556/92536655-9451aa80-f210-11ea-93f4-f201e3fdd153.png)

- Se podria deshabilitar el botón _asociar links_ cuando no hay ningun link cargado?
- Me paso que: agregué 2 links y los guardé. Toqué editar, clickeé en borrar 1 y borro ambos. Esta bien ese comportamiento?

2020-09-09 00:53 UTC, julieta-foglia commented
@ThomiReynoso listo el primero y el segundo. No se deshabilita porque si entra a editar tiene que permitir guardar si quiere borrar todos (no habría links agregados). Lo tercero no lo puedo reproducir.

2020-09-10 23:15 UTC, micaderito approved these changes

2020-09-10 23:16 UTC, merged