Feature/dev 164 - subir y visualizar correcciones
Equipo102ProyectoUNLaM/trida pull request #91
Opened 2020-09-11 21:12 UTC by maticairo

En esta PR se agrega la funcionalidad de subir archivos en la seccion de prácticas y visualizarlas en la sección de correcciones. Para probar:

 - Ir al módulo de prácticas logueado como alumno
 - Subir una práctica con mensaje y archivo
 - Ir a la sección de correcciones como alumno/docente y visualizar la práctica cargada.

WIP: filtrar por estado las prácticas para que cuando el alumno la sube ya no la vea más "pendiente"

2020-09-12 04:22 UTC, LautaroPerez requested changes
Encontre algunos detalles:
- En la sección de correcciones (loggeado como usuario), el titulo dice Mis Practicas.
- Tambien en la sección de correcciones, las correcciones listadas muestran el nombre del alumno (siempre va a ser el alumno loggeado)
- Los iconos de subir y descargar son muy parecidos.
- Cuando cargo la práctica, aparece la notificacion de editada y cargada.
- Como opcion momentanea hasta que esté el filtrado de practicas entregadas, podriamos cambiar el icono que muestra.
- Hay forma de poner el nombre de archivo que se está cargando? Sino solo dice archivo adjunto y no se sabe bien que se está subiendo.

2020-09-12 15:37 UTC, julieta-foglia commented
Coincido con Lauti en los íconos. Quizás podemos poner botones con texto en lugar de íconos, sería un cambio re chiquito.
Agregaría del lado del docente el botón 'corregir' como estaba antes, aunque por ahora no haga nada, pero que ya tenga la info del archivo específico a corregir (se puede dejar un console.log del nombre del id del archivo o algo así)

2020-09-13 01:41 UTC, LautaroPerez approved these changes
Excelente! Queda para ver despues, el tema de cambiar el boton de subir por uno de subida luego de entregar la practica

2020-09-13 17:23 UTC, julieta-foglia approved these changes

2020-09-14 16:27 UTC, merged