Feature/dev 189 - características especiales en evaluación
Equipo102ProyectoUNLaM/trida pull request #92
Opened 2020-09-12 21:15 UTC by micaderito

En esta PR se agregan las opciones de agregar características a las evaluaciones:
 - Preguntas aleatorias
 - No tomar capturas de pantalla
 - No salir de la ventana
 - Mensaje al alumno cuando se seleccionan alguna de estas características (menos preguntas aleatorias)

Para probar:
- Crear una evaluación y seleccionar alguna de las opciones
- Editarla y verificar que aparezcan los datos cargados
- Entrar como alumno y verificar que se muestren los mensajes correspondientes.

NOTA: No incluye funcionalidades, solo son la carga de opciones

2020-09-13 02:02 UTC, LautaroPerez requested changes
Habría algun texto en especial en el caso de que no tenga seleccionada ninguna de las dos? 
Aparte de esto, me paso que cuando fui a resolver la evaluación como alumno, en la lista de evaluaciones se agrega un nuevo registro pero todo en blanco (No tiene que ver con este PR pero quizas sabes que puede llegar a ser):
![image](https://user-images.githubusercontent.com/31162985/93008523-08ab8700-f54c-11ea-89f3-adc548aa8c5a.png)

2020-09-13 02:07 UTC, LautaroPerez approved these changes
Fabuloso

2020-09-13 02:16 UTC, LautaroPerez approved these changes
Excelente fabuloso genial

2020-09-15 00:52 UTC, julieta-foglia approved these changes
Pio la

2020-09-15 03:17 UTC, merged